### ISSUE TITLE
test: drop BaseWebContextSensitiveTest from 7 pure-logic tests that never use Spring

### ISSUE THREAD

**Issue by Agaba-derrick** [DIGI-UW/OpenELIS-Global-2#4394]
### Affected Component / Area

Testing (JUnit / Playwright / Cypress)

### 👾 Description of the Issue

Seven test classes extend `BaseWebContextSensitiveTest`, which boots a full Spring context and a PostgreSQL container on every run. None of these seven classes use `@Autowired`, load fixture data, or interact with the database in any way — they test pure Java logic. Extending the heavy base class for them adds unnecessary startup time to the suite and sets a bad example for contributors who copy these files as a starting point for new tests.

**Files affected (one PR can cover all 7):**

| File | What it actually tests |
|---|---|
| `AnalyzerFhirImportControllerTest` | Pure controller mapping logic |
| `SamplePatientUpdateDataSamplingSiteTest` | Sampling site field validation |
| `SamplePatientUpdateDataValidateTest` | `validateSample` field-error type |
| `NonConformityRecordNumberValidationProviderTest` | String validation logic |
| `ProviderIdParameterIntegrationTest` | Provider ID parameter parsing |
| `AuthenticatedAnalyzerControllerTest` | Auth controller logic |
| `SpringContextTestIsolationTest` | Context isolation assertion |

### 💡 Proposed Solution

For each of the 7 files listed above:

1. Remove `extends BaseWebContextSensitiveTest`.
2. Remove the Spring `@RunWith(SpringRunner.class)` if present (keep `@RunWith(MockitoJUnitRunner.class)` if Mockito is used in that test).
3. Confirm no field in the class actually relies on Spring wiring (`@Autowired`, `@MockBean`, fixture/dataset loading) before removing — if one is found, leave that file out of this cleanup and note it in the PR instead of forcing the change.
4. Run `mvn test -Dtest=<ClassName>` to confirm the test still passes after the change.

**Reference — good pattern to copy:** `UserProgramsTest` — plain JUnit + Mockito, no Spring context.

This is scoped entirely to the test layer (`src/test/java`); no production code changes are required.

### 👩‍💻 Implementation Steps (End-to-End)

- Run `mvn test -Dtest=<ClassName>` individually for each of the 7 modified classes to confirm they still pass without the Spring context.
- Run the full test suite (`mvn test`) to confirm no other tests relied on shared state or context set up by these classes.
- No new tests are required — this is a refactor of existing tests, not new coverage

**Comment by r-afael** [comment]
I audited all seven classes on current `develop` (`cfb18c05`). The absence of `@Autowired` fields in the test classes does not make these tests independent of Spring.

| Class | Dependency |
| --- | --- |
| `AnalyzerFhirImportControllerTest` | [Uses the inherited web context and MockMvc](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/test/java/org/openelisglobal/analyzerimport/action/AnalyzerFhirImportControllerTest.java#L41); setup replaces fields on the managed controller and teardown restores them. It also reads the bridge JSON fixture. |
| `SamplePatientUpdateDataSamplingSiteTest` | [Inserts and reads sampling-site rows](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/test/java/org/openelisglobal/sample/action/util/SamplePatientUpdateDataSamplingSiteTest.java#L30) through the real `VectorSamplingSiteService`. |
| `SamplePatientUpdateDataValidateTest` | [SamplePatientUpdateData resolves Spring services during construction](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/sample/action/util/SamplePatientUpdateData.java#L111). [SampleAddService also initializes static Spring service references](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/common/services/SampleAddService.java#L64). Its `FormFields` initialization also reads Spring-managed configuration. Avoiding accession validation does not avoid those dependencies. |
| `NonConformityRecordNumberValidationProviderTest` | The format method initializes [DateUtil](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/common/util/DateUtil.java#L52), which calls [ConfigurationProperties.getInstance()](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/common/util/ConfigurationProperties.java#L372) and resolves a Spring bean. The existing `ExceptionInInitializerError` catch can make a context-free run appear to pass while skipping the format assertions and leaving `DateUtil` erroneous for later tests in the same JVM. |
| `ProviderIdParameterIntegrationTest` | The providers resolve services during [instance initialization](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/common/rest/provider/AllTestsForSampleTypeProviderRestController.java#L40) and [static initialization](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/main/java/org/openelisglobal/common/rest/provider/PendingAnalysisForTestProviderRestController.java#L49). The unknown numeric ID case queries real services. |
| `AuthenticatedAnalyzerControllerTest` | [Abstract helper](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/test/java/org/openelisglobal/analyzer/controller/AuthenticatedAnalyzerControllerTest.java#L15) with no test methods and no current subclasses. It does not start a context independently, so removing its superclass would not save a test startup. |
| `SpringContextTestIsolationTest` | [Directly tests the inherited context-restoration setup](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/cfb18c05e238bff3a4a552b45335eadf8f76b614/src/test/java/org/openelisglobal/SpringContextTestIsolationTest.java#L12), using `webApplicationContext` and `setDefaultTestAuthentication()`. |

Following the issue's instruction to leave context-dependent classes out, I found no safe removal to submit in this scope. I have left the tests and assertions unchanged. This needs a revised candidate list or an explicit scope to decouple selected tests; the persistence and context-isolation coverage should remain integration coverage.

I also compiled temporary copies outside the checkout with just the base import/inheritance removed and ran them in fresh JVMs: sampling-site 6/6 failed, validation 6/6 failed, and provider-ID 4/4 failed due to missing Spring initialization. The nonconformity copy reported 4 passes, but immediately loading `DateUtil` again threw `NoClassDefFoundError`, confirming the caught initialization error. No tracked files were changed for these probes.

Baseline validation on Java 21: all six concrete classes pass individually (24 tests total); selecting the abstract helper runs 0 tests. The full unchanged `mvn test` suite is still running.

**Comment by dharmendra26-wiz** [comment]
Opened a PR for this: #4398 . Covered 4 of the 7 files — the other 3 genuinely depend on Spring context (details in the PR description).

**Comment by Agaba-derrick** [comment]
Hi @r-afael,
Thank you for digging into this and testing each of the 7 classes on `develop`! Upon inspecting the source code of those 7 files, every single one has implicit runtime dependencies on Spring or the database that prevent simply dropping 
Since simply removing `BaseWebContextSensitiveTest` is not possible without deeper refactoring or mocking, I will update/rescope this issue so we don't send contributors down the wrong path. 
Thanks again for the thorough verification!
@dharmendra26-wiz , we shall first close #4398 as we re scope the issue

**Comment by saiprasad578** [comment]
Thanks @r-afael for the detailed verification, and @Agaba-derrick for moving quickly on the rescope — better to catch this now than merge tests that silently pass for the wrong reason.

One thing worth resolving before the rescope is finalized: @r-afael's findings (16 failing tests across sampling-site, validation, and provider classes; none of the 7 safely removable as-is) seem to conflict with #4398, which claims 4 of the 7 pass cleanly without the base class. Since #4394 is about to close #4398, it'd be worth a quick diff between the two lists — either #4398's 4 files overlap with ones @r-afael flagged as broken (in which case the PR needs a second look before closing), or they're a genuinely different subset that @r-afael didn't hit issues with (in which case those 4 might still be salvageable in the rescope rather than starting from zero).

For the rescoped issue itself, suggest splitting into two tracks so the "good first issue" label still points somewhere safe:

1. **Needs real refactoring** — sampling-site, validation, and provider classes that resolve Spring beans or hit the DB during init. These need the dependency actually mocked out (e.g. `DateUtil`'s init path mocked directly) before the base class can go — not a mechanical `extends` removal, so probably better as per-class sub-issues with a "what needs mocking" checklist rather than one bundled PR.

2. **Not cleanup candidates at all** — `SpringContextTestIsolationTest` (explicitly tests context isolation, so removing the context defeats its purpose) and `AuthenticatedAnalyzerControllerTest` (abstract, runs no tests on its own). Suggest dropping both from scope entirely rather than trying to rescope them.

Also worth stating explicitly in the rescoped description: the nonconformity test's silent-pass trap @r-afael found, where removing the base class makes `DateUtil`'s Spring init error get swallowed instead of surfacing, and the assertions after it just get skipped. That's the kind of failure a newcomer following the original "remove extends, run the test, see green" steps would walk straight into.

Just a suggestion for whoever ends up scoping this — happy for anyone to run with it.
